language: php

php:
  - 5.6

install:
  - composer self-update

before_script:
  - mv .env.travis .env
  - mv travis.phpunit.xml phpunit.xml
  - mysql -e 'create database test_condor;'
  - composer install --dev --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  - php artisan config:cache
  - php artisan route:cache
  - php artisan optimize

after_success:
  - ./travis-codeclimate-report.sh
